### ISSUE TITLE
NotFittedError

### ISSUE THREAD

**Issue by ch3njust1n** [mouradmourafiq/tensorflow-lstm-regression#10]
I get the following error from just running the code as is.

Traceback (most recent call last):
  File "lstmSort.py", line 33, in <module>
    p=regressor.predict(X['test'])
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 237, in predict
    return self._predict(x, axis=axis, batch_size=batch_size)
  File "/home/tensorflow/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 199, in _predict
    raise NotFittedError()
tensorflow.contrib.learn.python.learn.estimators._sklearn.NotFittedError

**Comment by mouradmourafiq** [comment]
Hi @ch3njust1n, it could be due some requirements issues. Can you pull and check again?
